language: java
dist: bionic
sudo: false
git:
  depth: false
cache:
  directories:
  - $HOME/.m2
addons:
  sonarcloud:
    organization: "svenpeldszus-github"
    token: ${SONAR_TOKEN]
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -fae -Dsonar.projectKey=GRaViTY-SecDFD-Mapping -Dmaven.javadoc.skip=true -DtrimStackTrace=false
